blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
    path('blog/', views.IndexView.as_view(), name='index'),
    # ex: /blog

    path('blog/create', views.create_post, name='create_post'),
    #ex: /blog/create

    path('blog/delete/<int:pk>', views.DeletePost.as_view(), name='delete_post'),

    path('account/register', views.register, name='register'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('polls/', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('polls/<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('polls/<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('polls/<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/create/
    path('polls/create/', views.createPage, name='create_page'),
    # ex: /polls/create/object/
    path('polls/create/object', views.create, name='create'),
    # ex: /polls/create/choice/
    path('polls/create/choice', views.CreateChoicePage.as_view(), name='create_choice_page'),
    # ex: /polls/What's going on/create
    path('polls/delete/<int:pk>/', views.deleteView.as_view(), name='delete_question'),
    # ex: polls/delete/32

    path('polls/create/choice/<int:pk>', views.create_choice, name='create_choice'),

    path('', views.newIndex, name='dashboard_index'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post_title = models.CharField(max_length=200, help_text='Type the name of the field.')
    pub_date = models.DateTimeField(default=timezone.now)
    post_content = models.TextField(help_text='Type in the blog post.')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def current_time(self):
        return timezone.now()

    def __str__(self):
        return self.post_title
    class Meta:
        permissions = (("can_delete_posts", "Manage posts as needed"),)

polls/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200, null=True)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timezone.timedelta(days=1)

    def __str__(self):
        return str(self.question_text)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render
from django.views import generic
from django.http import *
from .models import *
from django.urls import reverse
# Create your views here.
from django.contrib.auth.decorators import login_required

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all()

@login_required
def create_post(request):
    query = Post.objects.all()

    if request.POST:
        title = request.POST.get('title')
        content = request.POST.get('content')
        user = request.POST.get('user')
        real = User.objects.get(id=user)
        obj = Post(post_title=title, post_content=content, writer=real)
        obj.save()
        return HttpResponseRedirect('/blog')
    else:
        return render(request, template_name='blog/create.html', context={'posts':query})

class DeletePost(generic.DeleteView):
    model = Post
    success_url = '/blog'
    template_name = 'blog/confirm_delete.html'

def register(request):
    all_users = User.objects.all()

    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.create_user(username=username, password=password)
        user.save()
        return HttpResponseRedirect(reverse('blog:index'))

    else:
        return render(request, template_name='registration/register.html', context={'all_users':all_users})

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:15]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_question = question.choice_set.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question':question, 'error_message': "You didn't select a choice"})
    else:
        selected_question.votes += 1
        selected_question.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def createPage(request):

    return render(request=request, template_name='polls/create.html', context={})

@login_required
def create(request):

    if request.POST:
        name = request.POST.get('text_name')
        date = timezone.now()
        q = Question(question_text=name, pub_date=date)
        q.save()
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return HttpResponse('You failed.')

class CreateChoicePage(generic.ListView):
    model = Question
    template_name = 'polls/choices.html'
    context_object_name = 'questions'

    def get_queryset(self):
        return Question.objects.all()



class deleteView(generic.DeleteView):

    template_name='polls/confirm_delete.html'
    model = Question
    success_url = '/polls/'


#def create_choice_page(request):
    #return render(request, template_name='polls/choice_form')
@login_required
def create_choice(request, pk):
    question = get_object_or_404(Question, pk=pk)
    choices = question.choice_set.all()

    if request.POST:
        choice = request.POST.get('choice_name')
        question.choice_set.create(choice_text=choice, votes=0)
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return render(request, template_name='polls/choices_create.html', context={'choices': choices})

def newIndex(request):
    return render(request, template_name='dashboard/index.html')

blog/templates/blog/confirm_delete.html
{% extends 'dashboard/docs/index.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block header_title %} Confirm Deletion {% endblock %}
{% block header_content %} Sure you ain't fucked up, pal? Wanna delete this shit? {% endblock %}
{% block content %}
    </ul>
    {% if perms.blog.can_delete_posts %}
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    </form>

        {% else %}
        <p>Only authenticated users can delete posts.</p>
    {% endif %}

{% endblock %}





</body>
</html>

blog/templates/blog/create.html
{% extends 'dashboard/docs/index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block header_title %} Create Post {% endblock %}
{% block header_content %} Here's where you write your glorious blog posts. Or shitty. Depends on you. {% endblock %}
{% block content %}

    </ul>
    <form method="post">
    {% csrf_token %}
        <div class="bs">
        <ul class="list-group">
            <li class="list-group-item">  Title:   <input type="text" name="title" class="form-control"></li><br>
            <li class="list-group-item"><label>Content:</label> <textarea rows="4" cols="50" name="content" class="form-control">
</textarea> </li><br>
            <input type="hidden" name="user" value="{{ user.id }}">
    <input type="submit">
        </ul>
        </div>

    </form>
{% endblock %}
</body>
</html>

blog/templates/blog/index.html
{% extends 'dashboard/docs/index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Blog Post {% endblock %}</title>
</head>
<body>


{% block sidebar %}
    {% for post in posts %}
        <li><a href="#{{ post.post_title }}" id="markdown-toc-contents">{{ post.post_title }}</a></li>
    {% endfor %}
{% endblock %}
{% block content %}

<button type="button" class="ce oa nl" onclick="location.href='{% url 'blog:create_post' %}'"><span class="bv bec"></span> Create Post</button>
    {% for post in posts %}

    <h1 id="intro">{{ post.post_title }}</h1>
    <p id="{{ post.post_title }}">By {{ post.writer}} at: {{ post.pub_date }}</p>
    <p>{{ post.post_content }}</p>
        <p><button type="button" class="ce oa no" onclick="location.href='{% url 'blog:delete_post' post.id %}'"><span class="bv bnl"></span> Delete</button>
</p>

        <p><hr></p>
    {% endfor %}
{% endblock %}
</body>
</html>

polls/templates/dashboard/docs/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<!-- Mirrored from bootstrap-themes.github.io/dashboard/docs/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Nov 2018 22:21:05 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <title>
        {% block title %}      {% endblock %}
    </title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">
    
      <link href="{% static 'blog/assets/css/toolkit-inverse.css' %}" rel="stylesheet">
    
    
      <link href="{% static 'blog/assets/css/docs.css' %}" rel="stylesheet">
    
    <link href="{% static 'blog/assets/css/application.css' %}" rel="stylesheet">

    <style>
      /* note: this is a hack for ios iframe for bootstrap themes shopify page */
      /* this chunk of css is not part of the toolkit :) */
      body {
        width: 1px;
        min-width: 100%;
        *width: 100%;
      }
    </style>
  </head>


<body class="axs">

  <nav class="ci pl adm ps tn app-navbar">
    <a class="pg" href="{% url 'polls:dashboard_index' %}">
      <span class="bv bhc axt"></span>
      Dashboard
    </a>

    <button
      class="pj brm vi"
      type="button"
      data-toggle="collapse"
      data-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="pk"></span>
    </button>

    <div class="collapse pi" id="navbarResponsive">
      <ul class="nav navbar-nav ahm">
        <li class="pa">
          <a class="oy" href="{% url 'polls:index' %}">Polls</a>
        </li>
        <li class="pa active">
          <a class="oy" href="{% url 'blog:index' %}">Blog</a>
        </li>
          {% if user.is_authenticated %}
              <li class="pa"><a class="oy" style="color:deepskyblue">{{ user }}</a></li>
              <li class="pa"><a class="oy" href="{% url 'logout' %}">Logout</a></li>

              {% else %}
                    <li class="pa"><a class="oy" href="{% url 'login' %}">Login</a></li>

          {% endif %}

      </ul>
    </div>
  </nav>


  
    <div class="bt" id="content">
      <div class="bw">
        <h1>{% block header_title %}Blog List {% endblock %}</h1>
        <p>{% block header_content %}Here we have the list of blog posts. You can make a post, delete or edit one.
        You can only post if you register, and can only delete if you have such permissions. Try it!{% endblock %}</p>
      </div>
    </div>
    <div class="bw docs-content">
      
<h1 id="contents">Contents</h1>
<ul id="markdown-toc">
  <li><a href="" id="markdown-toc-contents">Posts</a></li>
{% block sidebar %}

    {% endblock %}
    </ul>
    {% block content %}


    {% endblock %}
    </div>
  

    <script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/chart.js' %}"></script>
    <script src="{% static 'blog/assets/js/tablesorter.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/toolkit.js' %}"></script>
    <script src="{% static 'blog/assets/js/application.js' %}"></script>
    <script>
      // execute/clear BS loaders for docs
      $(function(){while(window.BS&&window.BS.loader&&window.BS.loader.length){(window.BS.loader.pop())()}})
    </script>
  </body>

<!-- Mirrored from bootstrap-themes.github.io/dashboard/docs/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Nov 2018 22:21:05 GMT -->
</html>

polls/templates/polls/create.html
{% extends 'dashboard/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Create Question {% endblock %}</title>
</head>
<body>
{% block content_title_1 %}
Voice your Concerns
{% endblock %}
{% block content_title_2 %}
Create a Question
{% endblock %}
{% block content %}
<form action="{% url 'polls:create' %}" method="post">
    {% csrf_token %}
    <p>Create a question with the following caption below:</p>
    <input type="text" name="text_name">
    <input type="submit" name="submit">

</form>

{% endblock %}
</body>
</html>

polls/templates/polls/detail.html
{% extends 'dashboard/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Question Detail {% endblock %}</title>
</head>
<body>
{% block content_title_1 %}
Got any more of them stolen elections?
{% endblock %}
{% block content_title_2 %}
    Question Detail
{% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>

        <br>
{% endfor %}
<input type="submit" value="Vote">
    </form>
{% endblock %}
</body>
</html>

polls/templates/polls/index.html
{% extends 'dashboard/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <title>{% block title %}Polls App{% endblock %}</title>
</head>
<body>
{% block content_title_1 %}
Welcome to the Polls!
{% endblock %}

{% block content %}
    <h1>How does it work?</h1>
    <p>Click on the question's name to vote on it. Click on delete to do exactly what you think it does. Click add a choice
    to add some other choice to vote to.</p>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <ol class="ql">

        <li class="qm"><a href={% url 'polls:detail' question.id %}>{{ question.question_text }}</a>
            /
            <a href="{% url 'polls:delete_question' question.id %}"> [Delete] </a>
            /
            <a href="{% url 'polls:create_choice' question.id %}"> [Add a Choice]</a>
        </li>
            </ol>
        {% endfor %}


        <a href="{% url 'polls:create_page' %}">Click here if you want to create a poll question.</a><br>
        <p><a href="{% url 'polls:dashboard_index' %}">Click here to go the other index.</a></p>


    {% else %}
        <p>No polls were available.</p>
        <a href="{% url 'polls:create_page' %}">Create one here.</a>
{% endif %}
{% endblock %}
</body>
</html>

polls/templates/polls/results.html
{% extends 'dashboard/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Election Results {% endblock %}</title>
</head>
<body>
{% block content_title_1 %}
And the winner is..
{% endblock %}
{% block content_title_2 %}
Poll Results
{% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a><br>
<a href="{% url 'polls:dashboard_index' %}">Return to Main page?</a>
{% endblock %}
</body>
</html>

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from bootstrap-themes.github.io/dashboard/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Nov 2018 22:18:57 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <title>
        {% block title %}
            Hello World
        {% endblock %}


    </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">

      <link href="{% static 'polls/assets/css/toolkit-inverse.css' %}" rel="stylesheet">


    <link href="{% static 'polls/assets/css/application.css'%}" rel="stylesheet">

    <style>
      /* note: this is a hack for ios iframe for bootstrap themes shopify page */
      /* this chunk of css is not part of the toolkit :) */
      body {
        width: 1px;
        min-width: 100%;
        *width: 100%;
      }
    </style>
  </head>


<body>
  <div class="bw">
    <div class="dh">
      <div class="en bpz">
        <nav class="bqg">
          <div class="bqa">
            <button class="bow boy bqb" type="button" data-toggle="collapse" data-target="#nav-toggleable-md">
              <span class="adp">Toggle nav</span>
            </button>
            <a class="bqc brd" href="{% url 'polls:dashboard_index' %}">
              <span class="bv bhc bqd"></span>
            </a>
          </div>

          <div class="collapse bpd" id="nav-toggleable-md">
            <form class="bqe">
              <input class="form-control" type="text" placeholder="Search...">
              <button type="submit" class="nz">
                <span class="bv bhw"></span>
              </button>
            </form>
            <ul class="nav pb nav-stacked wz">
              <li class="axq">Applications</li>
                {% block sidebar %}
                    <li class="pa"><a class="oy" href="{% url 'polls:index' %}">Polls</a></li>
                    <li class="pa"><a class="oy" href="{% url 'blog:index' %}">Blog</a></li>

                {% endblock %}
            </ul>
            <hr class="bre aez">
          </div>
        </nav>
      </div>
      <div class="et brf">
        <div class="bqn">
  <div class="bqo">
    <h6 class="bqq">{% block content_title_1 %}GNU-Django{% endblock %}</h6>
    <h2 class="bqp">{% block content_title_2 %}Overview{% endblock %}</h2>
  </div>

  <div class="on bqr">
    <div class="axm bpy">
      <input type="text" value="01/01/15 - 01/08/15" class="form-control" data-provide="datepicker">
      <span class="bv bbc"></span>
    </div>
  </div>
</div>

<hr class="aez">
{% block content %}


{% endblock %}

</div>
      </div>
    </div>
  </div>

  <div id="docsModal" class="cb fade" tabindex="-1" role="dialog" aria-labelledby="brl">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="sd">
        <h4 class="modal-title" id="myModalLabel">Example modal</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p>You're looking at an example modal in the dashboard theme.</p>
      </div>
      <div class="se">
        <button type="button" class="ce ni" data-dismiss="modal">Cool, got it!</button>
      </div>
    </div>
  </div>
</div>


    <script src="{% static 'polls/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'polls/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'polls/assets/js/chart.js' %}"></script>
    <script src="{% static 'polls/assets/js/tablesorter.min.js' %}"></script>
    <script src="{% static 'polls/assets/js/toolkit.js' %}"></script>
    <script src="{% static 'polls/assets/js/application.js' %}"></script>
    <script>
      // execute/clear BS loaders for docs
      $(function(){while(window.BS&&window.BS.loader&&window.BS.loader.length){(window.BS.loader.pop())()}})
    </script>
  </body>

<!-- Mirrored from bootstrap-themes.github.io/dashboard/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Nov 2018 22:18:58 GMT -->
</html>

templates/dashboard/docs/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<!-- Mirrored from bootstrap-themes.github.io/dashboard/docs/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Nov 2018 22:21:05 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <title>
        {% block title %}      {% endblock %}
    </title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">
    
      <link href="{% static 'blog/assets/css/toolkit-inverse.css' %}" rel="stylesheet">
    
    
      <link href="{% static 'blog/assets/css/docs.css' %}" rel="stylesheet">
    
    <link href="{% static 'blog/assets/css/application.css' %}" rel="stylesheet">

    <style>
      /* note: this is a hack for ios iframe for bootstrap themes shopify page */
      /* this chunk of css is not part of the toolkit :) */
      body {
        width: 1px;
        min-width: 100%;
        *width: 100%;
      }
    </style>
  </head>


<body class="axs">

  <nav class="ci pl adm ps tn app-navbar">
    <a class="pg" href="{% url 'polls:dashboard_index' %}">
      <span class="bv bhc axt"></span>
      Dashboard
    </a>

    <button
      class="pj brm vi"
      type="button"
      data-toggle="collapse"
      data-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="pk"></span>
    </button>

    <div class="collapse pi" id="navbarResponsive">
      <ul class="nav navbar-nav ahm">
        <li class="pa">
          <a class="oy" href="{% url 'polls:index' %}">Polls</a>
        </li>
        <li class="pa active">
          <a class="oy" href="{% url 'blog:index' %}">Blog</a>
        </li>
          {% if user.is_authenticated %}
              <li class="pa"><a class="oy" style="color:deepskyblue">{{ user }}</a></li>
              <li class="pa"><a class="oy" href="{% url 'logout' %}">Logout</a></li>

              {% else %}
                    <li class="pa"><a class="oy" href="{% url 'login' %}">Login</a></li>

          {% endif %}

      </ul>
    </div>
  </nav>


  
    <div class="bt" id="content">
      <div class="bw">
        <h1>{% block header_title %}Blog List {% endblock %}</h1>
        <p>{% block header_content %}Here we have the list of blog posts. You can make a post, delete or edit one.
        You can only post if you register, and can only delete if you have such permissions. Try it!{% endblock %}</p>
      </div>
    </div>
    <div class="bw docs-content">
      
<h1 id="contents">Contents</h1>
<ul id="markdown-toc">
  <li><a href="" id="markdown-toc-contents">Posts</a></li>
{% block sidebar %}

    {% endblock %}
    </ul>
    {% block content %}


    {% endblock %}
    </div>
  

    <script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/chart.js' %}"></script>
    <script src="{% static 'blog/assets/js/tablesorter.min.js' %}"></script>
    <script src="{% static 'blog/assets/js/toolkit.js' %}"></script>
    <script src="{% static 'blog/assets/js/application.js' %}"></script>
    <script>
      // execute/clear BS loaders for docs
      $(function(){while(window.BS&&window.BS.loader&&window.BS.loader.length){(window.BS.loader.pop())()}})
    </script>
  </body>

<!-- Mirrored from bootstrap-themes.github.io/dashboard/docs/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 11 Nov 2018 22:21:05 GMT -->
</html>